### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Jeremyop** [Flash-1337/OutlookGenerator#12]
![image](https://user-images.githubusercontent.com/101853820/209470168-7c7dfad7-0c5b-424f-aeaf-3de98e672cbf.png)

**Comment by phasephasephase** [comment]
do you have firefox installed

**Comment by skullcheat** [comment]
Same here firefox installed +tested with chromedriver and gekodriver not working ='(

**Comment by phasephasephase** [comment]
make sure geckodriver is in the same folder as the account generator

**Comment by skullcheat** [comment]
[https://i.postimg.cc/yN4Nn1X7/Untitled.png](url)

**Comment by skullcheat** [comment]
Fixed ... lolll thanks
