### ISSUE TITLE
Small inssues

### ISSUE THREAD

**Issue by RafaelYepez** [Flash-1337/OutlookGenerator#7]
Very good script! Congratulation!

The problem is that sometimes firefox don't run, or get erros.
You should add accont save only when script finished.
File accounts.json save account but is not the same created.

Good job with spoof fingeprind for get easy captchas, it's is aweosome, do you know how do it without you script? I wanna get less captchas manually, can you teach me how get it?

**Comment by Flash-1337** [comment]
NO nn
